# Generated by Django 6.1.1 on 2026-09-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_base', '0003_mensaje_telegram_ba_tipo_ev_27568c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código tal como aparece en el canal: OP408, A960, 1243', max_length=20, unique=True)),
                ('codigo_normalizado', models.CharField(db_index=True, help_text='Uppercase sin espacios ni guiones: OP408, A960, 1243', max_length=20)),
                ('direccion', models.TextField(blank=True, help_text='Dirección/cuadrante que provee la empresa en el mensaje.')),
                ('municipio', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subestacion', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del centro del cuadrante.', max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del centro del cuadrante.', max_digits=9, null=True)),
                ('geometria_geojson', models.JSONField(blank=True, help_text='Polígono opcional del cuadrante (GeoJSON) para Folium.', null=True)),
                ('estado', models.CharField(choices=[('afectado', 'Afectado'), ('en_servicio', 'En servicio'), ('desconocido', 'Desconocido')], db_index=True, default='desconocido', max_length=20)),
                ('estado_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('estado_origen', models.CharField(blank=True, choices=[('afectacion', 'Mensaje de afectación'), ('restablecimiento', 'Mensaje de restablecimiento'), ('inferido', 'Inferido / histórico')], max_length=20)),
                ('afectacion_inicio_msg', models.DateTimeField(blank=True, null=True)),
                ('afectacion_inicio_contenido', models.DateTimeField(blank=True, null=True)),
                ('afectacion_fin_msg', models.DateTimeField(blank=True, null=True)),
                ('afectacion_fin_contenido', models.DateTimeField(blank=True, null=True)),
                ('afectacion_duracion_msg_min', models.PositiveIntegerField(blank=True, null=True)),
                ('afectacion_duracion_contenido_min', models.PositiveIntegerField(blank=True, null=True)),
                ('afectacion_activa', models.BooleanField(default=False, help_text='True si aún no llegó el mensaje de restablecimiento.')),
                ('servicio_inicio_msg', models.DateTimeField(blank=True, null=True)),
                ('servicio_inicio_contenido', models.DateTimeField(blank=True, null=True)),
                ('servicio_fin_msg', models.DateTimeField(blank=True, null=True)),
                ('servicio_fin_contenido', models.DateTimeField(blank=True, null=True)),
                ('servicio_duracion_msg_min', models.PositiveIntegerField(blank=True, null=True)),
                ('servicio_duracion_contenido_min', models.PositiveIntegerField(blank=True, null=True)),
                ('servicio_activo', models.BooleanField(default=False, help_text='True si aún no llegó el mensaje de afectación siguiente.')),
                ('total_afectaciones', models.PositiveIntegerField(default=0)),
                ('total_minutos_afectado', models.PositiveIntegerField(default=0, help_text='Suma acumulada de minutos afectado (por mensaje).')),
                ('primera_mencion', models.DateTimeField(blank=True, null=True)),
                ('ultima_mencion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['estado', '-estado_actualizado_en'], name='circuitos_c_estado_df835a_idx'), models.Index(fields=['codigo_normalizado'], name='circuitos_c_codigo__8c7c25_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoCircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('afectacion', 'Afectación'), ('restablecimiento', 'Restablecimiento'), ('mencion', 'Mención')], db_index=True, max_length=20)),
                ('fecha_mensaje', models.DateTimeField(help_text='msg.fecha (UTC del post en Telegram).')),
                ('fecha_contenido', models.DateTimeField(blank=True, help_text='Hora mencionada en el texto del mensaje (si existe).', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='circuitos.circuito')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_circuito', to='telegram_base.mensaje')),
            ],
            options={
                'verbose_name': 'Evento de circuito',
                'verbose_name_plural': 'Eventos de circuitos',
                'ordering': ['fecha_mensaje'],
                'indexes': [models.Index(fields=['circuito', 'fecha_mensaje'], name='circuitos_e_circuit_95990a_idx'), models.Index(fields=['circuito', 'tipo', 'fecha_mensaje'], name='circuitos_e_circuit_2fcd1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('circuito', 'mensaje'), name='unico_evento_circuito_mensaje')],
            },
        ),
    ]
