# Generated by Django 6.1.1 on 2026-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='usar_cuadrado_default',
            field=models.BooleanField(default=True, help_text='Si True, se dibuja un cuadrado genérico cuando no hay geometria_geojson. Si False, el circuito solo se dibuja si tiene un geojson real.'),
        ),
    ]
