# Generated by Django 6.1.1 on 2026-09-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0002_circuito_usar_cuadrado_default'),
        ('telegram_base', '0003_mensaje_telegram_ba_tipo_ev_27568c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='estado_comunitario',
            field=models.CharField(choices=[('afectado', 'Afectado (reportes)'), ('en_servicio', 'En servicio (reportes)'), ('intermitente', 'Intermitente (reportes)'), ('sin_reportes', 'Sin reportes')], db_index=True, default='sin_reportes', max_length=20),
        ),
        migrations.AddField(
            model_name='circuito',
            name='estado_comunitario_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='reportes_usuarios_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AlertaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('occidente', 'Apagón en occidente'), ('oriente', 'Apagón en oriente'), ('habana', 'Apagón en La Habana'), ('total', 'Apagón total (toda la isla)'), ('parcial', 'Apagón parcial')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('iniciado_en', models.DateTimeField(db_index=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='True mientras la home muestre el modo apagón.')),
                ('reportes_usuarios', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('mensaje_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_masivas', to='telegram_base.mensaje')),
                ('mensaje_fin_oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_cerradas', to='telegram_base.mensaje')),
            ],
            options={
                'verbose_name': 'Alerta masiva',
                'verbose_name_plural': 'Alertas masivas',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('afectado', 'Sin servicio'), ('en_servicio', 'Con servicio'), ('intermitente', 'Intermitente')], max_length=20)),
                ('comentario', models.TextField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='circuitos.alertamasiva')),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_usuarios', to='circuitos.circuito')),
            ],
            options={
                'verbose_name': 'Reporte de usuario',
                'verbose_name_plural': 'Reportes de usuarios',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['circuito', '-creado_en'], name='circuitos_r_circuit_44e2a1_idx'), models.Index(fields=['ip_hash', '-creado_en'], name='circuitos_r_ip_hash_004574_idx')],
            },
        ),
    ]
