# Generated by Django 6.1.1 on 2026-09-17 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0003_circuito_estado_comunitario_and_more'),
        ('telegram_base', '0003_mensaje_telegram_ba_tipo_ev_27568c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotAverias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('circuitos_afectados', models.JSONField(default=list, help_text='Lista de códigos de circuito reportados como afectados.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_averias', to='telegram_base.mensaje')),
            ],
            options={
                'verbose_name': 'Snapshot de averías',
                'verbose_name_plural': 'Snapshots de averías',
                'ordering': ['-fecha'],
            },
        ),
    ]
