# Generated by Django 6.1.1 on 2026-09-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0004_snapshotaverias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='estado_origen',
            field=models.CharField(blank=True, choices=[('afectacion', 'Mensaje de afectación'), ('restablecimiento', 'Mensaje de restablecimiento'), ('inferido', 'Inferido / histórico'), ('reportes_usuarios', 'Consenso de reportes')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteDiscrepancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reportado', models.CharField(choices=[('sin_luz', 'Sin luz'), ('intermitente', 'Intermitente')], default='sin_luz', max_length=20)),
                ('comentario', models.TextField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('cambio_estado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_discrepancia', to='circuitos.circuito')),
            ],
            options={
                'verbose_name': 'Reporte de discrepancia',
                'verbose_name_plural': 'Reportes de discrepancia',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['circuito', '-creado_en'], name='circuitos_r_circuit_539c4f_idx'), models.Index(fields=['ip_hash', 'circuito', '-creado_en'], name='circuitos_r_ip_hash_f9de3d_idx')],
            },
        ),
    ]
