# Generated by Django 6.1.1 on 2026-09-17 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0005_alter_circuito_estado_origen_reportediscrepancia'),
        ('telegram_base', '0003_mensaje_telegram_ba_tipo_ev_27568c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitoDAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(db_index=True)),
                ('hasta', models.DateField(db_index=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_daf', to='circuitos.circuito')),
                ('mensaje_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_daf', to='telegram_base.mensaje')),
            ],
            options={
                'verbose_name': 'Circuito DAF',
                'verbose_name_plural': 'Circuitos DAF',
                'ordering': ['-desde', 'circuito__codigo'],
                'indexes': [models.Index(fields=['activo', '-desde'], name='circuitos_c_activo_dd160d_idx')],
            },
        ),
    ]
