# Generated by Django 6.1.1 on 2026-09-11 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_id_escaneado', models.BigIntegerField(default=0, help_text='ID del último mensaje procesado. El próximo scrape empieza aquí.')),
                ('ultimo_scrape', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado del scraper',
                'verbose_name_plural': 'Estado del scraper',
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ok', 'Completado'), ('parcial', 'Parcial'), ('error', 'Error'), ('en_curso', 'En curso')], default='en_curso', max_length=10)),
                ('id_inicio', models.BigIntegerField()),
                ('id_fin', models.BigIntegerField(blank=True, null=True)),
                ('mensajes_nuevos', models.IntegerField(default=0)),
                ('mensajes_actualizados', models.IntegerField(default=0)),
                ('ids_vacios', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ejecución de scraping',
                'verbose_name_plural': 'Ejecuciones de scraping',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID numérico del mensaje en Telegram (el de la URL).', unique=True)),
                ('texto', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha de publicación en UTC (la del atributo datetime).', null=True)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('tipo_media', models.CharField(choices=[('texto', 'Texto'), ('foto', 'Foto'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], default='texto', max_length=20)),
                ('enlace', models.URLField(max_length=300)),
                ('es_afectacion', models.BooleanField(default=False, help_text="True si el texto menciona 'afectó el servicio' o similar.")),
                ('circuitos_mencionados', models.JSONField(blank=True, default=list, help_text="Lista de códigos de circuito detectados (ej: ['OP408', 'P105']).")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-telegram_id'],
                'indexes': [models.Index(fields=['-telegram_id'], name='telegram_ba_telegra_9b9f42_idx'), models.Index(fields=['-fecha'], name='telegram_ba_fecha_2540f4_idx'), models.Index(fields=['es_afectacion'], name='telegram_ba_es_afec_340e6e_idx')],
            },
        ),
    ]
