# Generated by Django 6.1.1 on 2026-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='tipo_evento',
            field=models.CharField(choices=[('afectacion', 'Afectación'), ('restablecimiento', 'Restablecimiento'), ('otro', 'Otro')], db_index=True, default='otro', help_text='Clasificación del mensaje: afectación, restablecimiento u otro.', max_length=20),
        ),
    ]
