# Generated by Django 6.1.1 on 2026-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_base', '0002_mensaje_tipo_evento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['tipo_evento'], name='telegram_ba_tipo_ev_27568c_idx'),
        ),
    ]
