# Generated by Django 6.1.1 on 2026-09-17 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuitos', '0005_alter_circuito_estado_origen_reportediscrepancia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_push', models.BooleanField(default=False, help_text='Notificaciones Web Push (requiere permiso del navegador)')),
                ('notif_afectacion', models.BooleanField(default=True, help_text='Notificar cuando un circuito vinculado se afecte')),
                ('notif_restablecimiento', models.BooleanField(default=True, help_text='Notificar cuando un circuito vinculado se restablezca')),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='CircuitoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='circuitos.circuito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuitos_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Circuito vinculado',
                'verbose_name_plural': 'Circuitos vinculados',
                'ordering': ['circuito__codigo'],
                'constraints': [models.UniqueConstraint(fields=('user', 'circuito'), name='unico_usuario_circuito')],
            },
        ),
        migrations.CreateModel(
            name='NavegacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('metodo', models.CharField(max_length=10)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navegacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Navegación',
                'verbose_name_plural': 'Navegaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['user', '-creado_en'], name='usuarios_na_user_id_cb3d66_idx'), models.Index(fields=['-creado_en'], name='usuarios_na_creado__554959_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('afectacion', 'Afectación'), ('restablecimiento', 'Restablecimiento'), ('sistema', 'Mensaje del sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('enlace', models.CharField(blank=True, max_length=300)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dedup_key', models.CharField(blank=True, db_index=True, help_text='Clave única para deduplicar (ej: user:circuito:msg_id)', max_length=120)),
                ('circuito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='circuitos.circuito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['user', 'leida', '-creado_en'], name='usuarios_no_user_id_1d2bf9_idx')],
            },
        ),
    ]
